config/routes.rb
HmtGrocery::Application.routes.draw do
  devise_for :users

  resources :lists

  resources :stores

  resources :details

  resources :items
  
  root :to => "lists#index"

end

app/models/list.rb
class List < ActiveRecord::Base
  belongs_to :user
  belongs_to :item
  accepts_nested_attributes_for :item
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  # GET /lists
  # GET /lists.json
  def index
    @lists = List.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @lists }
    end
  end

  # GET /lists/1
  # GET /lists/1.json
  def show
    @list = List.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @list }
    end
  end

  # GET /lists/new
  # GET /lists/new.json
  def new
    @list = List.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @list }
    end
  end

  # GET /lists/1/edit
  def edit
    @list = List.find(params[:id])
  end

  # POST /lists
  # POST /lists.json
  def create
    @list = List.new(params[:list])

    respond_to do |format|
      if @list.save
        format.html { redirect_to @list, notice: 'List was successfully created.' }
        format.json { render json: @list, status: :created, location: @list }
      else
        format.html { render action: "new" }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /lists/1
  # PUT /lists/1.json
  def update
    @list = List.find(params[:id])

    respond_to do |format|
      if @list.update_attributes(params[:list])
        format.html { redirect_to @list, notice: 'List was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lists/1
  # DELETE /lists/1.json
  def destroy
    @list = List.find(params[:id])
    @list.destroy

    respond_to do |format|
      format.html { redirect_to lists_url }
      format.json { head :ok }
    end
  end
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/lists/_form.html.erb
<%= form_for(@list) do |f| %>
  <% if @list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@list.errors.count, "error") %> prohibited this list from being saved:</h2>

      <ul>
      <% @list.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :list %><br />
    <%= f.text_field :list %>
  </div>


<% @list.build_item unless @list.item %>
  <%= f.fields_for :item do |g| %>
    <%= g.label :name %><br />
    <%= g.text_field :name %><br />
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/lists/_store-form.html.erb
<%= form_for(store) do |f| %>
  <% if store.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(store.errors.count, "error") %> prohibited this store from being saved:</h2>

      <ul>
      <% store.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
<%# f.hidden_field :item %>
  </div>
  <!--<div class="field">
    <%#= f.label :item_id %><br />
    <%#= f.number_field :item_id %>
  </div>
  <div class="field">
    <%#= f.label :detail_id %><br />
    <%#= f.number_field :detail_id %>
  </div>-->
<% store.build_detail unless store.detail %>
  <%= f.fields_for :detail do |g| %>
    <%= g.label :section %><br />
    <%= g.text_field :section %><br />
  <% end %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/lists/_store_fields.erb
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
<%# f.hidden_field :item %>
  </div>
  <!--<div class="field">
    <%#= f.label :item_id %><br />
    <%#= f.number_field :item_id %>
  </div>
  <div class="field">
    <%#= f.label :detail_id %><br />
    <%#= f.number_field :detail_id %>
  </div>-->
<% store.build_detail unless store.detail %>
  <%= f.fields_for :detail do |g| %>
    <%= g.label :section %><br />
    <%= g.text_field :section %><br />
  <% end %>

app/views/lists/_store_fields.html.erb
<%= form_for(store) do |f| %>
  <% if store.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(store.errors.count, "error") %> prohibited this store from being saved:</h2>

      <ul>
      <% store.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
<%# f.hidden_field :item %>
  </div>
  <!--<div class="field">
    <%#= f.label :item_id %><br />
    <%#= f.number_field :item_id %>
  </div>
  <div class="field">
    <%#= f.label :detail_id %><br />
    <%#= f.number_field :detail_id %>
  </div>-->
<% store.build_detail unless store.detail %>
  <%= f.fields_for :detail do |g| %>
    <%= g.label :section %><br />
    <%= g.text_field :section %><br />
  <% end %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/lists/edit.html.erb
<h1>Editing list</h1>

<%= render 'form' %>

<%= link_to 'Show', @list %> |
<%= link_to 'Back', lists_path %>

app/views/lists/index.html.erb
<h1>Listing lists</h1>

<table>
  <tr>
    <th>List</th>
    <!--<th>Item</th>
    <th>User</th>-->
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @lists.each do |list| %>
  <tr>
    <td><%= list.list %></td>
    <!--<td><%#= list.item_id %></td>
    <td><%#= list.user_id %></td>-->
    <td><%= link_to 'Show', list %></td>
    <td><%= link_to 'Edit', edit_list_path(list) %></td>
    <td><%= link_to 'Destroy', list, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New List', new_list_path %>

app/views/lists/new.html.erb
<h1>New list</h1>

<%#= render :partial => 'store-form', :locals => {:store => Store.new }%>

<%= render 'form' %>

<%= link_to 'Back', lists_path %>

app/views/lists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>List:</b>
  <%= @list.list %>
</p>
<%#= @list.item.name %>

<!--<p>
  <b>Item:</b>
  <%#= @list.item_id %>
</p>

<p>
  <b>User:</b>
  <%#= @list.user_id %>
</p>-->


<%= link_to 'Edit', edit_list_path(@list) %> |
<%= link_to 'Back', lists_path %>