config/routes.rb
HmtGrocery::Application.routes.draw do
  devise_for :users

  resources :lists

  resources :stores

  resources :details

  resources :items
  
  root :to => "lists#index"

end

app/models/detail.rb
class Detail < ActiveRecord::Base
  has_many :items, :through => :stores
  has_many :stores
end

app/controllers/details_controller.rb
class DetailsController < ApplicationController
  # GET /details
  # GET /details.json
  def index
    @details = Detail.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @details }
    end
  end

  # GET /details/1
  # GET /details/1.json
  def show
    @detail = Detail.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @detail }
    end
  end

  # GET /details/new
  # GET /details/new.json
  def new
    @detail = Detail.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @detail }
    end
  end

  # GET /details/1/edit
  def edit
    @detail = Detail.find(params[:id])
  end

  # POST /details
  # POST /details.json
  def create
    @detail = Detail.new(params[:detail])

    respond_to do |format|
      if @detail.save
        format.html { redirect_to @detail, notice: 'Detail was successfully created.' }
        format.json { render json: @detail, status: :created, location: @detail }
      else
        format.html { render action: "new" }
        format.json { render json: @detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /details/1
  # PUT /details/1.json
  def update
    @detail = Detail.find(params[:id])

    respond_to do |format|
      if @detail.update_attributes(params[:detail])
        format.html { redirect_to @detail, notice: 'Detail was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /details/1
  # DELETE /details/1.json
  def destroy
    @detail = Detail.find(params[:id])
    @detail.destroy

    respond_to do |format|
      format.html { redirect_to details_url }
      format.json { head :ok }
    end
  end
end

app/helpers/details_helper.rb
module DetailsHelper
end

app/views/details/_form.html.erb
<%= form_for(@detail) do |f| %>
  <% if @detail.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@detail.errors.count, "error") %> prohibited this detail from being saved:</h2>

      <ul>
      <% @detail.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :section %><br />
    <%= f.text_field :section %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/details/edit.html.erb
<h1>Editing detail</h1>

<%= render 'form' %>

<%= link_to 'Show', @detail %> |
<%= link_to 'Back', details_path %>

app/views/details/index.html.erb
<h1>Listing details</h1>

<table>
  <tr>
    <th>Section</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @details.each do |detail| %>
  <tr>
    <td><%= detail.section %></td>
    <td><%= link_to 'Show', detail %></td>
    <td><%= link_to 'Edit', edit_detail_path(detail) %></td>
    <td><%= link_to 'Destroy', detail, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Detail', new_detail_path %>

app/views/details/new.html.erb
<h1>New detail</h1>

<%= render 'form' %>

<%= link_to 'Back', details_path %>

app/views/details/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Section:</b>
  <%= @detail.section %>
</p>


<%= link_to 'Edit', edit_detail_path(@detail) %> |
<%= link_to 'Back', details_path %>